/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author jianl
 */
public class JfrmJoMenus extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfrmJoMenus.class.getName());

    /**
     * Creates new form JfrmJoMenus
     */
    public JfrmJoMenus() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("Sistema de Vendas de livros");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuCadastro = new javax.swing.JMenu();
        jMniUsuarios = new javax.swing.JMenuItem();
        jMniClientes = new javax.swing.JMenuItem();
        jMniFornecedores = new javax.swing.JMenuItem();
        jMniLivros = new javax.swing.JMenuItem();
        jMnuMovimento = new javax.swing.JMenu();
        jMnuVenda = new javax.swing.JMenuItem();
        jMnuCompra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuCadastro.setText("Cadastro");

        jMniUsuarios.setText("Usuarios");
        jMnuCadastro.add(jMniUsuarios);

        jMniClientes.setText("Clientes");
        jMniClientes.addActionListener(this::jMniClientesActionPerformed);
        jMnuCadastro.add(jMniClientes);

        jMniFornecedores.setText("Fornecedores");
        jMniFornecedores.addActionListener(this::jMniFornecedoresActionPerformed);
        jMnuCadastro.add(jMniFornecedores);

        jMniLivros.setText("Livros");
        jMniLivros.addActionListener(this::jMniLivrosActionPerformed);
        jMnuCadastro.add(jMniLivros);

        jMenuBar1.add(jMnuCadastro);

        jMnuMovimento.setText("Movimento");

        jMnuVenda.setText("Venda");
        jMnuVenda.addActionListener(this::jMnuVendaActionPerformed);
        jMnuMovimento.add(jMnuVenda);

        jMnuCompra.setText("Compra");
        jMnuMovimento.add(jMnuCompra);

        jMenuBar1.add(jMnuMovimento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMniClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMniClientesActionPerformed

    private void jMniFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMniFornecedoresActionPerformed

    private void jMniLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniLivrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMniLivrosActionPerformed

    private void jMnuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JfrmJoMenus().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMniClientes;
    private javax.swing.JMenuItem jMniFornecedores;
    private javax.swing.JMenuItem jMniLivros;
    private javax.swing.JMenuItem jMniUsuarios;
    private javax.swing.JMenu jMnuCadastro;
    private javax.swing.JMenuItem jMnuCompra;
    private javax.swing.JMenu jMnuMovimento;
    private javax.swing.JMenuItem jMnuVenda;
    // End of variables declaration//GEN-END:variables
}
